### ISSUE TITLE
downloading data from WA+ server for Sheet4

### ISSUE THREAD

**Issue by Nitram-GGA** [wateraccounting/watools#2]
Hi, 

I am trying to generate the Sheet4 using your tool. I got stuck when trying to download Grey Water Footprint and Saturated Water Content from the WA+ server. The reason is that the path "/WaterAccounting_Guest/Static_WA_Datasets/" is no longer there.

I was able to get the arcmap grid file of Grey Water Footprint from "WaterAccounting_Guest/Products/TWC/v1/water/", convert it to TIF and just replace it in the code. However, I cannot find anywhere the Saturated Water Content file "wcsat_topsoil.tif". The 1km data of HiHydroSoils is no longer available at their website (I think). Could you please upload again the missing file and point me to the correct path?

FYI, the files that are failing to download the data are:
 ~\watools\Collect\TWC\DataAccess.py 
~\watools\Collect\HiHydroSoil\DataAccess.py

Thank you.

**Comment by CMicha** [comment]
The path to that dataset is currently at: /WaterAccounting_Guest/Products/HiHydroSoil/
We will not continue to provide access to this dataset in the future, we recommend obtaining the new version from: https://www.futurewater.eu/projects/hihydrosoil/
