### ISSUE TITLE
Shapefile Package for Water Accounting+ 

### ISSUE THREAD

**Issue by Shubham-AU** [wateraccounting/watools#4]
During the further installation process I am facing a new problem

PackagesNotFoundError: The following packages are not available from current channels:

  - shapefile
![wa2](https://user-images.githubusercontent.com/105045152/167245360-0ebcdd06-7413-4512-8266-159c0b3f20cb.jpeg)

**Comment by trngbich** [comment]
Hello,

It's a bit confusing, but the name of the "shapefile" package is pyshp
To install, please use:
`conda install pyshp`
